services:
  app:
    build: .
    image: suisei
    env_file:
      - .env
    restart: on-failure
  valkey:
    image: valkey/valkey
    restart: on-failure
    environment:
      - VALKEY_EXTRA_FLAGS="--save 60 1"
    volumes:
      - valkey:/data

volumes:
  valkey:
